### ISSUE TITLE
Rethink Facebook image resizing

### ISSUE THREAD

**Issue by rolandschuetz** [kozi/contao-opengraph#2]
I don't see any reason why you would provide a way crop to a manual set format for Facebook sharing. 

A) Down-sizing should not happen at all, Facebook likes them in a big format.
B) If an image is cropped, it should always be cropped to the by Facebook recommended 1:1.91 format. See https://developers.facebook.com/docs/sharing/best-practices#images

**Comment by kozi** [comment]
A) Contao resizing is used for using **important part definitions** introduced in Contao 3.4. See: http://rocksolidthemes.com/de/contao/blog/responsive-images-picture-contao
B) Using recommended size 1200 x 630
