### ISSUE TITLE
Add additional tags

### ISSUE THREAD

**Issue by rolandschuetz** [kozi/contao-opengraph#4]
For the image setting og:image:width and og:image:height would also improve the first time sharing speed.

og:locale and og:locale:alternate should be configured according to Contaos alternate settings:

    <meta property="og:locale" content="en_US" />            
    <meta property="og:locale:alternate" content="fr_FR" />  
    <meta property="og:locale:alternate" content="it_IT" />

**Comment by kozi** [comment]
What do you mean by *according to Contaos alternate settings*

**Comment by rolandschuetz** [comment]
The Contao changelanguage module adds the following html meta tags:
<link rel="alternate" hreflang="en" lang="en" href="default-en.html" title="Home"><link rel="alternate" hreflang="de" lang="de" href="default-de.html" title="Home">

In ModuleChangeLanguage.php
$GLOBALS['TL_HEAD'][] = '<link rel="alternate" hreflang="' . $arrRootPage['language'] . '" lang="' . $arrRootPage['language'] . '" href="' . ($domain . $href) . '" title="' . specialchars($pageTitle, true) . '"' . ($objPage->outputFormat == 'html5' ? '>' : ' />');

**Comment by kozi** [comment]
Schreibe mal auf deutsch weiter.

1) ModuleChangeLanguage.php kommt ja aus einer extra Erweiterung. Mir ist auch nicht klar wie ich diese Erweiterung "nutzen" sollte?!

2) In der root-Seite wird ja eine Sprache festgelegt. Diese ist aber eventuell nur 2-stellig (de, en, etc). Opengraph bzw. Facebook erwartet aber anscheinend eine 5-stellige Zeichenkette ll_CC (de_DE, en_US).  Ein automatisches Mapping ist in diesem Fall wohl nicht möglich.

**Comment by rolandschuetz** [comment]
Bitte wieder öffnen.

a) Das Thema og:image:width wurde komplett ignoriert.

b) Zu deinen Fragen:
1) Man kann ja schaun ob die viel genutze Erweiterung vorhanden ist und dann diese Daten verwenden
2) Natürlich kann man das mappen, es gibt ja für jede Sprache ein default locale.
