### ISSUE TITLE
og:image url is missing the domain

### ISSUE THREAD

**Issue by rolandschuetz** [kozi/contao-opengraph#7]
When I test my website using the [Facebook Object Debugger](https://developers.facebook.com/tools/debug/og/object/) the opengraph tags are invalid:

_Object at URL 'https://www.zentrumfuercitizenscience.at/en/citizen-science.html' of type 'website' is invalid because the given value 'files/images/social-media-share-photo.jpg' for property 'og:image:url' could not be parsed as type 'url'._

I guess the domain is missing here?

**Comment by rolandschuetz** [comment]
Is this repository still the main opengraph repository? If so I have a pull commit for this feature :)

**Comment by kozi** [comment]
YES it is.

Gruß Martin

**Comment by rolandschuetz** [comment]
Awesome, here you go.
https://github.com/kozi/contao-opengraph/pull/8

**Comment by rolandschuetz** [comment]
This is already fixed.
https://github.com/kozi/contao-opengraph/commit/68f86ae4597f23b23b67ca6f5ef1ef5d36ce8af2
